<!DOCTYPE HTML>
<html lang="en-GB">
	<head>
		<title>indieDex - Reviews</title>
		<link rel="icon" type="image/gif" href="img/indieDexpng.png"> 
		<meta charset="UTF-8">
		
		<!-- FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Monofett' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Dosis:400,500' rel='stylesheet' type='text/css'>
		
		<!-- STYLESHEETS -->
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
		<link rel="stylesheet" type="text/css" href="css/header.css"/>
		<link rel="stylesheet" type="text/css" href="css/button.css"/>
		<link rel="stylesheet" type="text/css" href="css/general.css"/>
		<link rel='stylesheet' type='text/css' href="css/camera.css" id='camera-css' media='all'>
		<link rel='stylesheet' type='text/css' href="css/statIcons.css"/>
		<link rel='stylesheet' type='text/css' href="css/accountSidebar.css"/>
		
		<!-- JAVASCRIPT -->
		<script type='text/javascript' src="js/libs/jquery-1.6.2.js"></script>
	  	<script type='text/javascript' src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	  	
	  	<script type='text/javascript' src="js/libs/html5shiv-printshiv.js"></script>
	  	        
	  	<script type='text/javascript' src='js/jquery.min.js'></script>
    	<script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
    	<script type='text/javascript' src='js/jquery.easing.1.3.js'></script> 
    	<script type='text/javascript' src='js/camera.js'></script>
	  	
	  	<script type='text/javascript' src="js/header.js"></script>
	  	<script type='text/javascript' src="js/expandContent.js"></script>
	  	<script type='text/javascript' src="js/changePage.js"></script>
	  	<script type='text/javascript' src="js/queryDB.js"></script>
	  	<script type='text/javascript' src="js/getContentFilters.js"></script>
	  	<script type='text/javascript' src="js/general.js"></script>
	  	<script type='text/javascript' src="js/updateSession.js"></script>		
			
		<script>
  
			jQuery(function(){
				
				jQuery('#camera_wrap_1').camera();
				
			});
		
		</script>
		
		<?php include 'loginform.inc.php'; ?>
		
  	</head>
  	
	<body id="body">
 		<div id="containerDeev">
 			
 			<div id="leftContainer">
 				<div id="logo">
 					<img class="fill" src="img/indieDexpng.png"/>
 					<h1 class="center">REVIEWS</h1>
 				</div>
 				
 				<div id="accountSidebar">
					<?php include 'profileSidebar.php' ?>
				</div>
					
				<?php
				include 'dVdA.php';
				if(!isDev()){
					if(!isMod()){
						if(!isPremium()){
							?>
							<div class="sidebarAdvertisement"><img class="fill" src="img/fantaad.png"/></div>
							<div class="sidebarAdvertisement"><img class="fill" src="img/subwayad.png"/></div>
							<?php
						}else{null;}
					}else{null;}
				}else{null;}
				?>
				
				<div id="onlineUsersSidebar">
					<h4 class="center">0 Users Online</h4>
					<!-- GENERATED BY phpCallsOnLoad.js -> phpCallsOnLoad_updateSession() -->
				</div>
				
 			</div> <!-- LEFT CONTAINER -->
 			
 			<?php include 'slideshow.php'; ?>
 				
 			<div id="rightContainerTwo">	
 									
 				<div id="contentContainer">
 					
 					<?php
	 				require 'contentAdd.php';
					addReviews();
	 				?>
 					
 					<div id="contentItemContainer">
 						
					</div> <!-- CONTENT ITEM CONTAINER -->
					
					
					<!-- Page Buttons -->
				
					<div style="display: table; margin: 0 auto;clear:both;">
						<br/>
						<div type="button" id="pageButtonFirst" class="button inline-block"><<</div>
						<div type="button" id="pageButton1" class="button inline-block">-</div>
						<div type="button" id="pageButton2" class="button inline-block">-</div>
						<div type="button" id="pageButton3" class="button inline-block">-</div>
						<div type="button" id="pageButton4" class="button inline-block">-</div>
						<div type="button" id="pageButton5" class="button inline-block">-</div>
						<div type="button" id="pageButtonLast" class="button inline-block">>></div>
						<div type="button" id="pageButtonIndex" class="button inline-block">...</div>
					</div>
					
				</div> <!-- CONTENT CONTAINER -->
				
					
				<div id="rightSidebarContainer">
					<div id="rightSidebar">
						
						<div class="container">
							<input id="searchBar" class="fill" type="text" value="Search Titles..." onfocus="this.value = '';" onblur="this.value = 'Search Titles...'; }">
						</div>
						
						<h3>Console</h3>
						<br/>
	 					<input id="hi" class="checkboxFilter" type="checkbox" name="Console" value="PC">PC<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="Mac">Mac<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="Linux">Linux<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="PS4">PS4<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="PS3">PS3<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="XboxOne">Xbox One<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="Xbox360">Xbox 360<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="WiiU">Wii U<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="Wii">Wii<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="IOS">IOS<br>
						<input class="checkboxFilter" type="checkbox" name="Console" value="Android">Android<br><br>
						
						<h3>Genre</h3>
						<br/>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="Action">Action<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="Adventure">Adventure<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="Music">Music<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="MMO">MMO<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="Puzzle">Puzzle<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="RPG">RPG<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="Shooter">Shooter<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="Sport">Sport<br>
						<input class="checkboxFilter" type="checkbox" name="Genre" value="Strategy">Strategy<br><br>
						
						<h3>Release</h3>
						<br/>
						<input class="checkboxFilter" type="checkbox" name="Release" value="BETA">BETA<br>
						<input class="checkboxFilter" type="checkbox" name="Release" value="2014">2014<br>
						<input class="checkboxFilter" type="checkbox" name="Release" value="2013">2013<br>
						<input class="checkboxFilter" type="checkbox" name="Release" value="2012">2012<br>
						<input class="checkboxFilter" type="checkbox" name="Release" value="2011">2011<br>
						<input class="checkboxFilter" type="checkbox" name="Release" value="pre2010">2010-<br><br>
						
						<h3>Star Rating</h3>
						<br/>
						<input class="checkboxFilter" type="checkbox" name="Rating" value="5">&#9733;&#9733;&#9733;&#9733;&#9733;<br>
						<input class="checkboxFilter" type="checkbox" name="Rating" value="4">&#9733;&#9733;&#9733;&#9733;<br>
						<input class="checkboxFilter" type="checkbox" name="Rating" value="3">&#9733;&#9733;&#9733;<br>
						<input class="checkboxFilter" type="checkbox" name="Rating" value="2">&#9733;&#9733;<br>
						<input class="checkboxFilter" type="checkbox" name="Rating" value="1">&#9733;<br><br>
						
						<h3>Price</h3>
						<br/>
						<input class="checkboxFilter" data-operator="=="  data-limit_low="25.00" data-limit_high="25.00" type="checkbox" name="Price" value="25more">£25.00<br>
						<input class="checkboxFilter" data-operator=">=<" data-limit_low="15.00" data-limit_high="25.00" type="checkbox" name="Price" value="15to25">£15.00 - £25.00<br>
						<input class="checkboxFilter" data-operator="<="  data-limit_low="0.00"  data-limit_high="15.00" type="checkbox" name="Price" value="15less">£15.00-<br>
						<input class="checkboxFilter" data-operator="=="  data-limit_low="0.00"  data-limit_high="0.00"  type="checkbox" name="Price" value="0">Free<br><br>
						
						<h3>Staff Picks</h3>
						<br/>
						<input class="checkboxFilter" type="checkbox" name="Staff" value="Staff">Staff Picks<br><br>
						
						<div id="clearFilters" class="button no-margin">Clear Filters</div>
						
	 				</div> <!-- RIGHT SIDEBAR -->
	 			</div> <!-- RIGHT SIDEBAR CONTAINER -->
 			
 			</div> <!-- RIGHT CONTAINER TWO -->
 				
			<header class=".headerFixed">
				<a href="index.php"><div class="headerChild">Home</div></a>
				<a href="review.php"><div class="headerChild">Reviews</div></a>
				<a href="games.php"><div class="headerChild">Games</div></a>
				<a href="store.php"><div class="headerChild">Store</div></a>
			</header>

 		</div> <!-- CONTAINER DEEV -->
	
		<footer>
			<div id="footer">
				
			</div>
		</footer>
	
		<?php include 'php/updateSession.php' ?>
	
	</body>
</HTML>