<!DOCTYPE HTML>
<html lang="en-GB">
	<head>
		<title>indieDex</title>
		<meta charset="UTF-8">
		
		<!-- FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Monofett' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Dosis:400,500' rel='stylesheet' type='text/css'>
		
		<!-- STYLESHEETS -->
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
		<link rel="stylesheet" type="text/css" href="css/header.css"/>
		<link rel="stylesheet" type="text/css" href="css/button.css"/>
		<link rel="stylesheet" type="text/css" href="css/general.css"/>
		<link rel='stylesheet' type='text/css' href="css/statIcons.css"/>
		<link rel='stylesheet' type='text/css' href="css/accountSidebar.css"/>
		<link rel='stylesheet' type='text/css' href="css/signup.css"/>
		
		<!-- JAVASCRIPT -->
		<script type='text/javascript' src="js/libs/jquery-1.6.2.js"></script>
	  	<script type='text/javascript' src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	  	        
	  	<script type='text/javascript' src='js/jquery.min.js'></script>
    	<script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
    	<script type='text/javascript' src='js/jquery.easing.1.3.js'></script> 
    	<script type='text/javascript' src='js/camera.js'></script>
	  	
	  	<script type='text/javascript' src="js/header.js"></script>
	  	<script type='text/javascript' src="js/expandContent.js"></script>
	  	<script type='text/javascript' src="js/changePage.js"></script>
	  	<script type='text/javascript' src="js/queryDB.js"></script>
	  	<script type='text/javascript' src="js/getContentFilters.js"></script>
	  	<script type='text/javascript' src="js/general.js"></script>
	  	<script type='text/javascript' src="js/updateSession.js"></script>
	  	
	  	<!--[if lt IE 9]>
     		<script src="html5shiv.js"></script>
		<![endif]-->
		
			
		<script>
  
			jQuery(function(){
				
				jQuery('#camera_wrap_1').camera();
				
			});
		
		</script>
		
		<?php 
			require_once 'core.inc.php';
			
			if(loggedin()) {
				header('Location: profile.php?user='. $_SESSION['username']);
			}
		 ?>
		
  	</head>
  	
	<body id="body">
 		<div id="containerDeev">
 			
 			<div id="leftContainer">
 				<div id="logo">
 					<img class="fill" src="img/indieDexpng.png"/>
 					<h1 class="center">HOME</h1>
 				</div>
 				
 				<div id="accountSidebar">
					<?php include 'profileSidebar.php' ?>
				</div>
					
				<?php
				include 'dVdA.php';
				if(!isDev()){
					if(!isMod()){
						if(!isPremium()){
							?>
							<div class="sidebarAdvertisement"><img class="fill" src="img/fantaad.png"/></div>
							<div class="sidebarAdvertisement"><img class="fill" src="img/subwayad.png"/></div>
							<?php
						}else{null;}
					}else{null;}
				}else{null;}
				?>
				
				<div id="onlineUsersSidebar">
					<h4 class="center">0 Users Online</h4>
					<!-- GENERATED BY phpCallsOnLoad.js -> phpCallsOnLoad_updateSession() -->
				</div>
				
 			</div> <!-- LEFT CONTAINER -->
 			
 			<div class="rightContainer">
 				
 				<div id="signupContainer">
	 				<table id="signupDescriptions">
	 					<tr>
		 					<td>
		 						<h5>Non-Premium</h5>
		 						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec elit at erat pharetra lobortis semper in augue. Sed nulla nisl, pellentesque quis diam pellentesque, congue lobortis eros. Pellentesque eget fermentum massa. Mauris faucibus elit tellus, vitae vestibulum nisi malesuada eu. Mauris sapien turpis, euismod id neque eget, malesuada molestie justo. Maecenas sed ligula luctus, ultrices enim in, fermentum erat. Quisque scelerisque feugiat tincidunt. Curabitur vestibulum euismod vulputate. Aenean condimentum tortor quis laoreet condimentum. Vivamus id pretium turpis, eget dignissim velit. Aliquam placerat lectus sed leo luctus euismod.</p>
		 					</td>
		 					
		 					<td>
		 						<h5>Premium</h5>
		 						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec elit at erat pharetra lobortis semper in augue. Sed nulla nisl, pellentesque quis diam pellentesque, congue lobortis eros. Pellentesque eget fermentum massa. Mauris faucibus elit tellus, vitae vestibulum nisi malesuada eu. Mauris sapien turpis, euismod id neque eget, malesuada molestie justo. Maecenas sed ligula luctus, ultrices enim in, fermentum erat. Quisque scelerisque feugiat tincidunt. Curabitur vestibulum euismod vulputate. Aenean condimentum tortor quis laoreet condimentum. Vivamus id pretium turpis, eget dignissim velit. Aliquam placerat lectus sed leo luctus euismod.</p>
		 					</td>
		 					
		 					<td>
		 						<h5>Get The App</h5>
		 						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec elit at erat pharetra lobortis semper in augue. Sed nulla nisl, pellentesque quis diam pellentesque, congue lobortis eros. Pellentesque eget fermentum massa. Mauris faucibus elit tellus, vitae vestibulum nisi malesuada eu. Mauris sapien turpis, euismod id neque eget, malesuada molestie justo. Maecenas sed ligula luctus, ultrices enim in, fermentum erat. Quisque scelerisque feugiat tincidunt. Curabitur vestibulum euismod vulputate. Aenean condimentum tortor quis laoreet condimentum. Vivamus id pretium turpis, eget dignissim velit. Aliquam placerat lectus sed leo luctus euismod.</p>
		 					</td>
	 					</tr>
	 				</table>
	 				
	 				<div id="signupFormContainer">
	 					<div id="signupFormInner">
		 					<table id="signupForm" class="left">
		 						<form action="registerUser.php" method="post" enctype="multipart/form-data">
		 							
		 						<tr>
		 							<th>*Username:</th>
		 							<td><input type="text" name="user" placeholder="Must be between 4 and 18 chars"></td>
		 						</tr>
		 						
		 						<tr>
		 							<th>*Email Address:</th>
		 							<td><input type="text" name="email" placeholder="Must be a valid email address"></td>
		 						</tr>
		 						
		 						<tr>
		 							<th>*Password:</th>
		 							<td><input type="password" name="pass" placeholder="Must be between 6 and 32 chars"></td>
		 						</tr>
		 						
		 						<tr>
		 							<th>*Confirm Password:</th>
		 							<td><input type="password" name="confirmpass" placeholder="Must match your password"></td>
		 						</tr>
		 						
		 						
		 						
		 						<tr class="signupFormSkipRow"></tr>
		 						
		 						<tr>
		 							<th>First Name:</th>
		 							<td><input type="text" name="name"></td>
		 						</tr>
		 						
		 						<tr>
		 							<th>Surname:</th>
		 							<td><input type="text" name="surname"></td>
		 						</tr>
		 						
		 						<tr>
		 							<th>Birthday:</th>
		 							<td>
		 								<table> <tr>
				 								<td style="padding-right: 2%;"><input type="text" name="day"   placeholder="DD"> </td>
				 								<td style="padding: 1%;">      <input type="text" name="month" placeholder="MM"> </td>
				 								<td style="padding-left: 2%;"> <input type="text" name="year"  placeholder="YYYY"> </td>
			 							</tr> </table>
		 							</td>
		 						</tr>
		 						
		 						<tr>
		 							<th>Location:</th>
		 							<td><input type="text" name="location"></td>
		 						</tr>
		 						
		 						<tr class="signupFormSkipRow"></tr>
		 						
		 						<tr>
		 							<th colspan="2" style="padding: 0 25%; text-align: center;">After registering, check out your profile to add a picture and tell people about yourself!</th>
		 						</tr>
		 						
		 						<tr>
		 							<td colspan="2" style="text-align: center;"><input type="submit" value="Register"></td>
		 						</tr>
		 						
		 						</form>
		 					</table>
		 				</div>
	 				</div>
	 				
	 				<div class="clear"></div>
	 			</div>
 				
 			</div>
 				
			<header class=".headerFixed">
				<div class="headerChild">
					<a href="index.php"><div class="headerButton">Home</div></a>
					
	 				<div class="headerGrandchild">
	 					<ul>
	 						<a class="filterTop"  > <li>Top</li> </a>
	 						<a class="filterNew"  > <li>New</li> </a>
	 						<a class="filterHot"  > <li>Hot</li> </a>
	 						<a class="filterTrend"> <li>Trending</li> </a>
	 					</ul>
	 				</div>
				</div>
				
				<a href="review.php"><div class="headerChild">Reviews
					<div class="headerGrandchild">
						<ul>
							<a class="filterTop"  > <li>Top</li> </a>
	 						<a class="filterNew"  > <li>New</li> </a>
	 						<a class="filterHot"  > <li>Hot</li> </a>
	 						<a class="filterTrend"> <li>Trending</li> </a>
						</ul>
					</div>
				</div></a>
				
				<a href="games.php"><div class="headerChild">Games
					<div class="headerGrandchild">
						 <ul>
							<a class="filterTop"  > <li>Top</li> </a>
	 						<a class="filterNew"  > <li>New</li> </a>
	 						<a class="filterHot"  > <li>Hot</li> </a>
	 						<a class="filterTrend"> <li>Trending</li> </a>
						</ul>
					</div>
				</div></a>
				
				<a href="forum.php"><div class="headerChild">Forums
					<div class="headerGrandchild">
						<ul>
							<li>Top</li>
							<li>New</li>
							<li>Hot</li>
							<li>Trending</li>
						</ul>
					</div>
				</div></a>
			</header>

 		</div> <!-- CONTAINER DEEV -->
	
		<footer>
			<div id="footer">
				
			</div>
		</footer>
	
		<?php include 'php/updateSession.php' ?>
	
	</body>
</HTML>