<!DOCTYPE HTML>
<html lang="en-GB">
	<head>
		<title>indieDex</title>
		<meta charset="UTF-8">
		
		<!-- FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Monofett' rel='stylesheet' type='text/css'>
		
		<!-- STYLESHEETS -->
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
		<link rel="stylesheet" type="text/css" href="css/style.css"/>
		<link rel="stylesheet" type="text/css" href="css/header.css"/>
		<link rel="stylesheet" type="text/css" href="css/button.css"/>
		<link rel="stylesheet" type="text/css" href="css/general.css"/>
		<link rel='stylesheet' type='text/css' href="css/camera.css" id='camera-css' media='all'>
		<link rel='stylesheet' type='text/css' href="css/statIcons.css"/>
		<link rel='stylesheet' type='text/css' href="css/accountSidebar.css"/>
		<link rel="stylesheet" type="text/css" href="css/store.css"/>
		
		<!-- JAVASCRIPT -->
		<script type='text/javascript' src="js/libs/jquery-1.6.2.js"></script>
	  	<script type='text/javascript' src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	  	
	  	<script type='text/javascript' src="js/libs/html5shiv-printshiv.js"></script>
	  	        
	  	<script type='text/javascript' src='js/jquery.min.js'></script>
    	<script type='text/javascript' src='js/jquery.mobile.customized.min.js'></script>
    	<script type='text/javascript' src='js/jquery.easing.1.3.js'></script> 
    	<script type='text/javascript' src='js/camera.js'></script>
	  	
	  	<script type='text/javascript' src="js/header.js"></script>
	  	<script type='text/javascript' src="js/expandContent.js"></script>
	  	<script type='text/javascript' src="js/changePage.js"></script>
	  	<script type='text/javascript' src="js/queryDB.js"></script>
	  	<script type='text/javascript' src="js/getContentFilters.js"></script>
	  	<script type='text/javascript' src="js/general.js"></script>
	  	<script type='text/javascript' src="js/updateSession.js"></script>
	  	<script type='text/javascript' src="js/storeButtons.js"></script>
	
		<script>
  
			jQuery(function(){
				
				jQuery('#camera_wrap_1').camera();
				
			});
		
		</script>
		
		<?php include 'loginform.inc.php'; ?>
		
  	</head>
  	
	<body id="body">
 		<div id="containerDeev">
 			
 			<div id="leftContainer">
 				<div id="logo">
 					<img class="fill" src="img/indieDexpng.png"/>
 					<h1 class="center">STORE</h1>
 				</div>
 				
 				<div id="accountSidebar">
					<?php include 'profileSidebar.php' ?>
				</div>
					
				<?php
				include 'dVdA.php';
				if(!isDev()){
					if(!isMod()){
						if(!isPremium()){
							?>
							<div class="sidebarAdvertisement"><img class="fill" src="img/fantaad.png"/></div>
							<div class="sidebarAdvertisement"><img class="fill" src="img/subwayad.png"/></div>
							<?php
						}else{null;}
					}else{null;}
				}else{null;}
				?>
				
				<div id="onlineUsersSidebar">
					<h4 class="center">0 Users Online</h4>
					<!-- GENERATED BY phpCallsOnLoad.js -> phpCallsOnLoad_updateSession() -->
				</div>
				
 			</div> <!-- LEFT CONTAINER -->
 				
 			<div id="storeContainer">
 				
				<div id="storeButtonContainer">
					<div class="storeButton" id="storeButton_indieDex">indieDex</div>
					<div class="storeButton" id="storeButton_game1">Minecraft</div>
					<div class="storeButton" id="storeButton_game2">blah</div>
					<div class="storeButton" id="storeButton_game3">blah2</div>
					<div class="storeButton" id="storeButton_cart">cart</div>
				</div>

				<div id="storeIndieDex">
					<div id="storeItemsContainer">
						<div class="storeItem">
							
							<div class="storeItemImageCont">
								
									<img class="storeItemImage" src="img/indieDexStoreOne.png">
								
							</div>
							<div class="storeItemBar">
								<p>indieDex T-shirt [Male] - £14.94 <div class="button storeAddItem">Add</div></p>
							</div>
						</div>					
						
						<div class="storeItem">
			
							<div class="storeItemImageCont">
								
									<img class="storeItemImage" src="img/indieDexStoreTwo.png">
								
							</div>
							<div class="storeItemBar">
								<p>indieDex Mug - £9.99 <div class="button storeAddItem">Add</div></p>
							</div>	
							
						</div>
						
						<div class="storeItem">
							<div class="storeItemImageCont">
								
									<img class="storeItemImage" src="img/indieDexStoreFour.png">
								
							</div>
							<div class="storeItemBar">
								<p>indieDex Mousemat - £3.99 <div class="button storeAddItem">Add</div></p>
							</div>	
							
						</div>							
						
						
						<div class="storeItem">
							<div class="storeItemImageCont">
								
									<img class="storeItemImage" src="img/indieDexStoreFive.png">
								
							</div>
							<div class="storeItemBar">
								<p>indieDex Beanie - £8.99 <div class="button storeAddItem">Add</div></p>
							</div>	
						</div>
						
						<div class="storeItem">
							
							<div class="storeItemImageCont">
								
									<img class="storeItemImage" src="img/indieDexStoreThree.png">
								
							</div>
							<div class="storeItemBar">
								<p>indieDex T-shirt [Female] - £14.94 <div class="button storeAddItem">Add</div></p>
							</div>
						</div>	
												
						<div class="storeItem">
							<div class="storeItemImageCont">
								
								<img class="storeItemImage" src="img/indieDexStoreSix.png">
								
							</div>
							<div class="storeItemBar">
								<p>indieDex Bath Towel - £28.95 <div class="button storeAddItem">Add</div></p>
							</div>
						</div>
					</div>
				</div>
				
				<div id="storeGame1">
					<div id="storeItemsContainer">
						<div class="storeItem">a</div>
						
						<div class="storeItem">e</div>
						
						<div class="storeItem">i</div>
						
						<div class="storeItem">o</div>
						
						<div class="storeItem">u</div>
					</div>
				</div>
				
				<div id="storeGame2">
					<div id="storeItemsContainer">
						<div class="storeItem">a</div>
						
						<div class="storeItem">e</div>
						
						<div class="storeItem">i</div>
						
						<div class="storeItem">o</div>
						
						<div class="storeItem">u</div>
					</div>
				</div>
				
				<div id="storeGame3">
					<div id="storeItemsContainer">
						<div class="storeItem">a</div>
						
						<div class="storeItem">e</div>
						
						<div class="storeItem">i</div>
						
						<div class="storeItem">o</div>
						
						<div class="storeItem">u</div>
					</div>
				</div>
				
				<div id="storeCart">
					<div id="storeItemsContainer">
						<div class="storeItem">a</div>
						
						<div class="storeItem">e</div>
						
						<div class="storeItem">i</div>
						
						<div class="storeItem">o</div>
						
						<div class="storeItem">u</div>
					</div>
				</div>
				
			</div>
			
			<header class=".headerFixed">
					
				<a href="index.php"><div class="headerChild">Home</div></a>
				
				<a href="review.php"><div class="headerChild">Reviews</div></a>
				
				<a href="games.php"><div class="headerChild">Games</div></a>
				
				<a href="store.php"><div class="headerChild">Store</div></a>
			</header>

 		</div> <!-- CONTAINER DEEV -->
	
		<footer>
			<div id="footer">
				
			</div>
		</footer>
	
		<?php include 'php/updateSession.php' ?>
	
	</body>
</HTML>